### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by YoungEffort** [a597873885/webfunny-admin#1]
Error: ENOENT: no such file or directory, open 'E:\cyRepository\性能监控系统\webfunny-admin\webfunny\animateList.a57426d1.chunk.js'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:690:12)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by a597873885** [comment]
nginx报错的吗

**Comment by YoungEffort** [comment]
不是nginx，是运行node config.js就报错了，就是代码clone下来之后，第二步报错，还没到第三步nginx的配置

**Comment by a597873885** [comment]
E:\cyRepository\性能监控系统\webfunny-admin\webfunny\
你可先看下这个目录下是否有animateList.a57426d1.chunk.js这个文件

然后把报错的上下文也贴出来给我看下，比如我的是这样的：

===========================
= 正在执行编译，请等待... =
===========================

manifest.json  接口域名配置成功！
index.html  接口域名配置成功！
login.6ec9c3b5.chunk.js  接口域名配置成功！
common.ed720eef.js  接口域名配置成功！
showScreenShot.78e68f22.chunk.js  接口域名配置成功！
register.72e834ca.chunk.js  接口域名配置成功！
projectList.67626f20.chunk.js  接口域名配置成功！
createProject.6bb661d0.chunk.js  接口域名配置成功！
animateList.a57426d1.chunk.js  接口域名配置成功！
httpErrorDetail.aeb7c4bb.chunk.js  接口域名配置成功！
behaviorUserList.97b2d8c9.chunk.js  接口域名配置成功！
httpError.6387777f.chunk.js  接口域名配置成功！

**Comment by YoungEffort** [comment]
源码clone下来都没有webfunny这个文件夹啊

===========================
= 正在执行编译，请等待... =
===========================
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\cyRepository\性能监控系统\webfunny-admin\webfunny\animateList.a57426d1.chunk.js'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:690:12)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by a597873885** [comment]
@YoungEffort  请重新拉去新的代码，我做了调整，感谢你的反馈
