### ISSUE TITLE
后台启动了，接口访问报404

### ISSUE THREAD

**Issue by YoungEffort** [a597873885/webfunny-admin#3]
config.js改好了8011的

前端报错：
![image](https://user-images.githubusercontent.com/33588367/64419915-87b3e700-d0d0-11e9-8b2c-6537f308e4d4.png)
![image](https://user-images.githubusercontent.com/33588367/64419944-99958a00-d0d0-11e9-943c-4d10b0ef1be0.png)

后台启动：
Running node-supervisor with
  program 'bin/www'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node bin/www'
Watching directory 'E:\cyRepository\pre\webfunny-servers' for changes.
Press rs for restarting the process.

**Comment by a597873885** [comment]
你需要新建一个应用，配置mysql数据库
本地的接口应该都是 http://localhost:8011/server/project/list?webMonitorId=L_webmonitor
这种类似的模式

**Comment by YoungEffort** [comment]
本地接口是访问的8011
![image](https://user-images.githubusercontent.com/33588367/64527339-402f9400-d338-11e9-81c7-f94698156dfb.png)

**Comment by a597873885** [comment]
@YoungEffort 正常情况下，根目录下 logs/errors 下应该有对应的日志，可以看下能否找到原因

**Comment by YoungEffort** [comment]
404客户端错误，不会到服务器日志，没访问到服务器

**Comment by a597873885** [comment]
@YoungEffort  这个是我的失误，所有的报错都会以404呈现

**Comment by YoungEffort** [comment]
你重写了404状态码？

**Comment by YoungEffort** [comment]
看到了，数据库连接错误
