### ISSUE TITLE
新建接口访问报错

### ISSUE THREAD

**Issue by YoungEffort** [a597873885/webfunny-admin#4]
请求：
![image](https://user-images.githubusercontent.com/33588367/64545254-fd32e800-d35a-11e9-8f37-9a1581e01cee.png)

服务器错误日志：
![image](https://user-images.githubusercontent.com/33588367/64545093-b8a74c80-d35a-11e9-9ccc-be1839d6203f.png)

**Comment by a597873885** [comment]
这个是你的mysql拒绝了你的连接



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YoungEffort <notifications@github.com&gt;
发送时间: 2019年9月9日 23:37
收件人: a597873885/webfunny-admin <webfunny-admin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny-admin] 新建接口访问报错 (#4)




服务器错误日志：

**Comment by YoungEffort** [comment]
不好意思，mysql升级把数据库密码清掉了，感谢解答
